"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.leanTemplates = void 0;
exports.leanTemplates = [
    {
        templateId: "daily-shipment-control",
        title: "Daily Shipment Control",
        category: "Daily Control",
        owner: "Transportation Planner",
        cadence: "Daily start of shift",
        purpose: "Create a shared view of loads, exceptions, carrier risk, and commitments before work fragments into spreadsheets.",
        sourceReference: "Daily control board plus shipment execution review",
        prompts: [
            "Which shipments or loads are inside the next 24-hour execution window?",
            "Which commitments have no confirmed carrier, appointment, or tracking update?",
            "Which customer-facing promises need governed review before confirmation?",
        ],
        outputs: ["Priority load list", "Owner assignment", "Escalation candidates", "Customer-risk notes"],
        evidence: ["Open load list", "Carrier confirmation state", "Appointment or pickup window", "Customer promise notes"],
        governanceTrigger: "Any high-impact exception, missed appointment risk, or customer promise should route to Encompax review.",
    },
    {
        templateId: "carrier-award-review",
        title: "Carrier Award Review",
        category: "Governance",
        owner: "Transportation Planner",
        cadence: "Before award on risky loads",
        purpose: "Pressure-test carrier selection using rate, lane, capacity, safety, credit, and falloff risk before dispatch commitment.",
        sourceReference: "Carrier award review and market-rate check",
        prompts: [
            "Is the carrier trusted on this lane and equipment type?",
            "Does the buy rate preserve margin against sell rate and market median?",
            "Are safety, credit, insurance, and falloff indicators acceptable?",
        ],
        outputs: ["Award recommendation", "Risk flags", "Margin check", "Encompax signal when needed"],
        evidence: ["Carrier score", "Sell rate and buy rate", "Lane profile", "Insurance or credit status"],
        governanceTrigger: "Route carrier awards when score is low, carrier trust is unresolved, or margin is below target.",
    },
    {
        templateId: "root-cause-a3",
        title: "A3 Root Cause Brief",
        category: "Problem Solving",
        owner: "Process Owner",
        cadence: "After repeat exception",
        purpose: "Turn recurring operational friction into a structured improvement record.",
        sourceReference: "A3 report, 8D problem solving, RCPS 6W2H, and root-cause workbook",
        prompts: [
            "What is the observed condition and target condition?",
            "What evidence shows this is recurring or material?",
            "What countermeasure can be tested without creating new risk?",
        ],
        outputs: ["Problem statement", "Root cause hypothesis", "Countermeasure", "Follow-up metric"],
        evidence: ["Current condition", "Target condition", "Root-cause evidence", "Countermeasure owner"],
        governanceTrigger: "Route to Encompax when countermeasures change policy, customer commitments, or cross-system process rules.",
    },
    {
        templateId: "5s-workplace-readiness",
        title: "5S Workplace Readiness",
        category: "Standard Work",
        owner: "Site Lead",
        cadence: "Weekly or before launch",
        purpose: "Stabilize workspace, queue, and visual-control readiness before performance reviews.",
        sourceReference: "5S handbook, 5S facilitator guide, and Intro 5S deck",
        prompts: [
            "What should be sorted, set in order, cleaned, standardized, and sustained?",
            "Which visible controls tell the next operator what normal looks like?",
            "What owner and cadence keep the standard from drifting?",
        ],
        outputs: ["5S area score", "Visual control gaps", "Owner assignment", "Sustainment cadence"],
        evidence: ["Before/after observations", "Area checklist", "Missed standard notes", "Sustainment owner"],
        governanceTrigger: "Route to Encompax if a workplace-readiness gap creates safety, service, compliance, or customer-risk exposure.",
    },
    {
        templateId: "process-analysis",
        title: "Process Analysis Template",
        category: "Problem Solving",
        owner: "Process Analyst",
        cadence: "Before process redesign",
        purpose: "Break a workflow into steps, handoffs, wait states, rework, and decision points before deciding what should be automated.",
        sourceReference: "Process Analysis Template Master",
        prompts: [
            "Where does the process start and end?",
            "Which handoffs, waits, and rework loops create the most delay?",
            "Which decision points should remain human-governed?",
        ],
        outputs: ["Process map", "Bottleneck list", "Automation candidates", "Governance checkpoints"],
        evidence: ["Step inventory", "Cycle-time notes", "Exception frequency", "Decision checkpoint list"],
        governanceTrigger: "Route process redesign when a workflow change affects customer commitments, controls, or agent decision authority.",
    },
    {
        templateId: "strategy-execution",
        title: "Strategy to Execution Matrix",
        category: "Strategy",
        owner: "Business Owner",
        cadence: "Monthly operating review",
        purpose: "Translate strategic priorities into measurable operating work and governance checkpoints.",
        sourceReference: "Strategy to Execution Matrix and IBP executive narrative",
        prompts: [
            "Which strategy is this work meant to support?",
            "Which measures prove progress rather than activity?",
            "Which unresolved tradeoffs need governed decision support?",
        ],
        outputs: ["Strategic objective", "Operating metric", "Decision checkpoint", "Review cadence"],
        evidence: ["Objective statement", "Target metric", "Owner", "Review checkpoint"],
        governanceTrigger: "Route when strategy execution creates tradeoffs between margin, service, risk, capacity, or customer trust.",
    },
];
