"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SIL_BUSINESS_DOMAINS = exports.SIL_GOVERNANCE_SIGNAL_TYPES = exports.BID_STATES = exports.BROKERAGE_LOAD_STATES = exports.SHIPMENT_STATES = void 0;
exports.SHIPMENT_STATES = [
    "DRAFT",
    "PENDING",
    "BOOKED",
    "DISPATCHED",
    "AT_PICKUP",
    "IN_TRANSIT",
    "AT_DELIVERY",
    "DELIVERED",
    "CANCELED",
    "EXCEPTION",
];
exports.BROKERAGE_LOAD_STATES = [
    "LOAD_CREATED",
    "READY_TO_POST",
    "POSTED",
    "BIDDING",
    "CARRIER_SELECTED",
    "TENDERED",
    "ACCEPTED",
    "DISPATCHED",
    "IN_TRANSIT",
    "DELIVERED",
    "INVOICED",
    "CLOSED",
    "CANCELED",
];
exports.BID_STATES = [
    "RECEIVED",
    "SHORTLISTED",
    "REJECTED",
    "AWARDED",
    "WITHDRAWN",
    "EXPIRED",
];
exports.SIL_GOVERNANCE_SIGNAL_TYPES = [
    "LOAD_AT_RISK",
    "CARRIER_FALLOFF_RISK",
    "TENDER_RESPONSE_DELAY",
    "APPOINTMENT_BREACH_RISK",
    "LANE_RATE_EXCEPTION",
    "LOAD_BOARD_BID_OPPORTUNITY",
    "BROKER_MARGIN_RISK",
    "CARRIER_CREDIT_RISK",
    "CUSTOMER_DELIVERY_COMMITMENT_RISK",
    "SHIPMENT_EXECUTION_EXCEPTION",
    "MARKET_RATE_VOLATILITY",
];
exports.SIL_BUSINESS_DOMAINS = [
    "TRANSPORTATION",
    "FREIGHT_BROKERAGE",
    "SHIPMENT_VISIBILITY",
    "WAREHOUSE_OPERATIONS",
    "CUSTOMER_SERVICE",
    "FINANCE",
    "RISK",
];
